// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import * as path from "node:path";
import * as dotenv from "dotenv";
import { defineConfig } from "prisma/config";

// Load the monorepo root .env (two levels up from packages/db)
dotenv.config({ path: path.resolve(__dirname, "../../.env") });
// Also load a local .env if present (does not override existing vars)
dotenv.config();

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
